version: "3.9"

services:
  # PHP
  app:
    container_name: ${APP_NAME}-php
    ports:
      - "${PHP_PORT}:9000"
    build:
      context: ./
      dockerfile: docker/php/php.dockerfile
    restart: unless-stopped
    working_dir: /var/www/src
    volumes:
      - ./src/:/var/www/src
    networks:
      novarede:
        ipv4_address: ${NGINX_IP}

  # NGINX
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine3.17
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src/:/var/www/src
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      novarede:
        ipv4_address: ${PHP_IP}
    depends_on:
      - app

networks:
  novarede:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
